baseURL = "https://example.com"
title = "Your title"
themesDir = "../.."
theme = "nord-custom-m10c"
paginate = 8
PygmentsCodeFences = true
PygmentsStyle = "nord"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[params]
  author = "John Doe"
  description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
  menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/gohugoio"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/gohugoio"
  [[params.footer]]
    description = "Colors from"
    url = "https://www.nordtheme.com/"
    name = "Nord by ArcticIceStudio"

  [params.style]
    # primaryColor = "#8fbcbb" # Frost 1 (Blue)
    # primaryColor = "#88c0d0" # Frost 2 (Blue)
    # primaryColor = "#81a1c1" # Frost 3 (Blue)
    # primaryColor = "#5e81ac" # Frost 4 (Blue, default)
    # primaryColor = "#bf616a" # Aurora 1 (Red)
    # primaryColor = "#d08770" # Aurora 2 (Orange)
    # primaryColor = "#ebcb8b" # Aurora 3 (Yellow)
    # primaryColor = "#a3be8c" # Aurora 4 (Green)
    # primaryColor = "#b48ead" # Aurora 5 (Purple)