---
name: hugo publish

on:
  push:
    branches:
    - main

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.88.1'

    - name: Build
      run: hugo --minify
      working-directory: ./exampleSite

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        EXTERNAL_REPOSITORY: hhenrichsen/
        PUBLISH_BRANCH: pages
        PUBLISH_DIR: ./exampleSite/public
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        emptyCommits: false
        commitMessage: ${{ github.event.head_commit.message }}